In [1]:
# Dependencies and Setup
import pandas as pd
import numpy as np

In [2]:
# Read School and Student Data File and store into Pandas Data Frames
schoold=pd.read_csv("schools_complete.csv",encoding="ISO-8859-1")
studentd=pd.read_csv("students_complete.csv",encoding="ISO-8859-1")

In [3]:
schoold.head()

   School ID            school_name      type  size   budget
0          0      Huang High School  District  2917  1910635
1          1   Figueroa High School  District  2949  1884411
2          2    Shelton High School   Charter  1761  1056600
3          3  Hernandez High School  District  4635  3022020
4          4    Griffin High School   Charter  1468   917500

In [4]:
studentd.head()

,Student ID,student_name,gender,grade,school_name,reading_score,math_score
0,0,Paul Bradley,M,9th,Huang High School,66,79
1,1,Victor Smith,M,12th,Huang High School,94,61
2,2,Kevin Rodriguez,M,12th,Huang High School,90,60
3,3,Dr. Richard Scott,M,12th,Huang High School,67,58
4,4,Bonnie Ray,F,9th,Huang High School,97,84

In [5]:
#Merge data
datosc=pd.merge(schoold,studentd,how="left", on=["school_name", "school_name"])

In [6]:
#DataFcomplete
datosc.head()

,School ID,school_name,type,size,budget,Student ID,student_name,gender,grade,reading_score,math_score
0,0,Huang High School,District,2917,1910635,0,Paul Bradley,M,9th,66,79
1,0,Huang High School,District,2917,1910635,1,Victor Smith,M,12th,94,61
2,0,Huang High School,District,2917,1910635,2,Kevin Rodriguez,M,12th,90,60
3,0,Huang High School,District,2917,1910635,3,Dr. Richard Scott,M,12th,67,58
4,0,Huang High School,District,2917,1910635,4,Bonnie Ray,F,9th,97,84

# District Summary

In [7]:
#Calculate the total number of schools
Escuelas_total=len(datosc["school_name"].unique())
Escuelas_total

15

In [8]:
#Calculate the total number of students
Estudiantes_total=len(datosc["student_name"].unique())
Estudiantes_total

32715

In [9]:
#Calculate the total budget
Total_Budget=datosc.groupby("school_name")["budget"].unique().sum()
Total_Budget

array([24649428], dtype=int64)

In [10]:
#Calculate the total budget
Total_Budget.sum()

24649428

In [11]:
#Calculate the average math score
Math_avg=datosc["math_score"].mean()
Math_avg

78.98537145774827

In [12]:
#Calculate the average reading score
Read_avg=datosc["reading_score"].mean()
Read_avg

81.87784018381414

In [13]:
#Calculate the overall passing rate (overall average score), i.e. (avg. math score + avg. reading score)/2
ovavg_score=(Read_avg+Math_avg)/2
ovavg_score

80.43160582078121

In [14]:
#Calculate the percentage of students with a passing math score (70 or greater)
Pstudentsmath=(len(datosc.loc[datosc["math_score"]>=70])/len(datosc))*100
Pstudentsmath

74.9808526933878

In [15]:
#Calculate the percentage of students with a passing reading score (70 or greater)
Pstudentread=(len(datosc.loc[datosc["reading_score"]>=70])/len(datosc))*100
Pstudentread

85.80546336482001

In [17]:
#Create a dataframe to hold the above results
results={"Total Schools":Escuelas_total,
        "Total Students":Estudiantes_total,
         "Total Budget":[Total_Budget],
         "Average Math Score":[Math_avg],
         "Average Reading Score":[Read_avg],
         "% Passing Math":[Pstudentsmath],
         "% Passing Reading":[Pstudentread],
         "% Overall Passing Rate":[ovavg_score]}

# DISTRICT DATA FRAME RESULTS

In [18]:
dfr= pd.DataFrame(results)
dfr

,Total Schools,Total Students,Total Budget,Average Math Score,Average Reading Score,% Passing Math,% Passing Reading,% Overall Passing Rate
0,15,32715,[24649428],78.985371,81.87784,74.980853,85.805463,80.431606

# School Summary

In [19]:
Escuelas=datosc.groupby("school_name")["school_name"].unique().count()
Escuelas

15

In [35]:
Type=datosc.groupby("school_name")["type"].unique()
Type

school_name
Bailey High School       [District]
Cabrera High School       [Charter]
Figueroa High School     [District]
Ford High School         [District]
Griffin High School       [Charter]
Hernandez High School    [District]
Holden High School        [Charter]
Huang High School        [District]
Johnson High School      [District]
Pena High School          [Charter]
Rodriguez High School    [District]
Shelton High School       [Charter]
Thomas High School        [Charter]
Wilson High School        [Charter]
Wright High School        [Charter]
Name: type, dtype: object

In [20]:
#School Name,School Type,Total School Budget
Schoolbud=datosc.groupby(["school_name"])["budget"].unique()
Schoolbud

school_name
Bailey High School       [3124928]
Cabrera High School      [1081356]
Figueroa High School     [1884411]
Ford High School         [1763916]
Griffin High School       [917500]
Hernandez High School    [3022020]
Holden High School        [248087]
Huang High School        [1910635]
Johnson High School      [3094650]
Pena High School          [585858]
Rodriguez High School    [2547363]
Shelton High School      [1056600]
Thomas High School       [1043130]
Wilson High School       [1319574]
Wright High School       [1049400]
Name: budget, dtype: object

In [21]:
#Total Students
Students=datosc.groupby(["school_name"])["size"].unique()
Students

school_name
Bailey High School       [4976]
Cabrera High School      [1858]
Figueroa High School     [2949]
Ford High School         [2739]
Griffin High School      [1468]
Hernandez High School    [4635]
Holden High School        [427]
Huang High School        [2917]
Johnson High School      [4761]
Pena High School          [962]
Rodriguez High School    [3999]
Shelton High School      [1761]
Thomas High School       [1635]
Wilson High School       [2283]
Wright High School       [1800]
Name: size, dtype: object

In [22]:
PSB2=Schoolbud/Students
PSB2

school_name
Bailey High School       [628.0]
Cabrera High School      [582.0]
Figueroa High School     [639.0]
Ford High School         [644.0]
Griffin High School      [625.0]
Hernandez High School    [652.0]
Holden High School       [581.0]
Huang High School        [655.0]
Johnson High School      [650.0]
Pena High School         [609.0]
Rodriguez High School    [637.0]
Shelton High School      [600.0]
Thomas High School       [638.0]
Wilson High School       [578.0]
Wright High School       [583.0]
dtype: object

In [23]:
#Average Math Score
AMS=datosc.groupby(["school_name"])["math_score"].sum()/datosc.groupby(["school_name"])["size"].unique()
AMS

school_name
Bailey High School       [77.04843247588424]
Cabrera High School      [83.06189451022605]
Figueroa High School     [76.71176670057646]
Ford High School         [77.10259218692954]
Griffin High School      [83.35149863760218]
Hernandez High School    [77.28975188781014]
Holden High School       [83.80327868852459]
Huang High School        [76.62941378128214]
Johnson High School      [77.07246376811594]
Pena High School         [83.83991683991684]
Rodriguez High School    [76.84271067766942]
Shelton High School       [83.3594548551959]
Thomas High School        [83.4183486238532]
Wilson High School        [83.2742006132282]
Wright High School       [83.68222222222222]
dtype: object

In [24]:
#Average Reading Score
ARS=datosc.groupby(["school_name"])["reading_score"].sum()/datosc.groupby(["school_name"])["size"].unique()
ARS

school_name
Bailey High School       [81.03396302250803]
Cabrera High School      [83.97578040904197]
Figueroa High School     [81.15801966768396]
Ford High School         [80.74625775830594]
Griffin High School        [83.816757493188]
Hernandez High School     [80.9344120819849]
Holden High School       [83.81498829039812]
Huang High School        [81.18272197463148]
Johnson High School      [80.96639361478681]
Pena High School         [84.04469854469855]
Rodriguez High School    [80.74468617154288]
Shelton High School      [83.72572402044293]
Thomas High School       [83.84892966360856]
Wilson High School       [83.98948751642575]
Wright High School                  [83.955]
dtype: object

In [25]:
#% Passing MATH
passmath=datosc.loc[datosc["math_score"]>=70]
passmath

,School ID,school_name,type,size,budget,Student ID,student_name,gender,grade,reading_score,math_score
0,0,Huang High School,District,2917,1910635,0,Paul Bradley,M,9th,66,79
4,0,Huang High School,District,2917,1910635,4,Bonnie Ray,F,9th,97,84
5,0,Huang High School,District,2917,1910635,5,Bryan Miranda,M,9th,94,94
6,0,Huang High School,District,2917,1910635,6,Sheena Carter,F,11th,82,80
8,0,Huang High School,District,2917,1910635,8,Michael Roth,M,10th,95,87
9,0,Huang High School,District,2917,1910635,9,Matthew Greene,M,10th,96,84
10,0,Huang High School,District,2917,1910635,10,Andrew Alexander,M,10th,90,70
11,0,Huang High School,District,2917,1910635,11,Daniel Cooper,M,10th,78,77
12,0,Huang High School,District,2917,1910635,12,Brittney Walker,F,9th,64,79
13,0,Huang High School,District,2917,1910635,13,William Long,M,9th,71,79
15,0,Huang High School,District,2917,1910635,15,Dr. Jordan Carson,M,11th,94,88
17,0,Huang High School,District,2917,1910635,17,Kimberly Santiago,F,9th,74,75
19,0,Huang High School,District,2917,1910635,19,Brandi Lyons,F,9th,89,80
20,0,Huang High School,District,2917,1910635,20,Lisa Davis,F,10th,91,89
21,0,Huang High School,District,2917,1910635,21,Kristen Lopez,F,10th,90,77
22,0,Huang High School,District,2917,1910635,22,Kimberly Stewart,F,11th,99,84
24,0,Huang High School,District,2917,1910635,24,Chelsea Griffith,F,11th,85,73
25,0,Huang High School,District,2917,1910635,25,Cesar Morris,M,9th,92,70
26,0,Huang High School,District,2917,1910635,26,Melanie Decker,F,9th,63,85
29,0,Huang High School,District,2917,1910635,29,Nicole Brown,F,12th,90,88
30,0,Huang High School,District,2917,1910635,30,Bobby Harris,M,9th,94,99
32,0,Huang High School,District,2917,1910635,32,Candace Phelps,F,11th,93,90
34,0,Huang High School,District,2917,1910635,34,Steven Green,M,11th,65,74
36,0,Huang High School,District,2917,1910635,36,Kevin Bailey,M,10th,76,76
38,0,Huang High School,District,2917,1910635,38,Kimberly Mercado,F,12th,73,77
41,0,Huang High School,District,2917,1910635,41,Jennifer Parks,F,11th,85,95
42,0,Huang High School,District,2917,1910635,42,John Carlson,M,9th,65,89
43,0,Huang High School,District,2917,1910635,43,Megan Roberts,F,9th,66,90
45,0,Huang High School,District,2917,1910635,45,Heidi Jackson,F,11th,64,93
47,0,Huang High School,District,2917,1910635,47,Ellen Brown,F,11th,77,81
...,...,...,...,...,...,...,...,...,...,...,...
39140,14,Thomas High School,Charter,1635,1043130,39140,Cheyenne Hernandez,F,9th,76,99
39141,14,Thomas High School,Charter,1635,1043130,39141,Jonathan Sullivan,M,10th,86,93
39142,14,Thomas High School,Charter,1635,1043130,39142,Deborah Higgins DDS,F,10th,96,83
39143,14,Thomas High School,Charter,1635,1043130,39143,Steven Jackson,M,11th,71,93
39144,14,Thomas High School,Charter,1635,1043130,39144,Cristian Webster,M,12th,77,87
39145,14,Thomas High School,Charter,1635,1043130,39145,Audrey Fry,F,10th,94,74
39146,14,Thomas High School,Charter,1635,1043130,39146,Michael Carroll,M,9th,69,95
39147,14,Thomas High School,Charter,1635,1043130,39147,Raymond Hawkins,M,10th,88,81
39148,14,Thomas High School,Charter,1635,1043130,39148,Christopher Wilson,M,10th,89,89
39149,14,Thomas High School,Charter,1635,1043130,39149,Glenda Fletcher,F,11th,82,93
39150,14,Thomas High School,Charter,1635,1043130,39150,Jennifer Hamilton,F,11th,80,75
39151,14,Thomas High School,Charter,1635,1043130,39151,Shannon Williams,F,10th,84,73
39152,14,Thomas High School,Charter,1635,1043130,39152,Lori Moore,F,9th,98,84
39153,14,Thomas High School,Charter,1635,1043130,39153,William Hubbard,M,9th,80,75
39154,14,Thomas High School,Charter,1635,1043130,39154,Bradley Johnson,M,12th,91,71
39155,14,Thomas High School,Charter,1635,1043130,39155,John Brooks,M,10th,92,98
39156,14,Thomas High School,Charter,1635,1043130,39156,Stephanie Contreras,F,11th,79,95
39157,14,Thomas High School,Charter,1635,1043130,39157,Kristen Gonzalez,F,9th,79,94
39158,14,Thomas High School,Charter,1635,1043130,39158,Kari Holloway,F,10th,87,90
39159,14,Thomas High School,Charter,1635,1043130,39159,Kimberly Cabrera,F,11th,85,72
39160,14,Thomas High School,Charter,1635,1043130,39160,Katie Weaver,F,11th,89,86
39161,14,Thomas High School,Charter,1635,1043130,39161,April Reyes,F,10th,70,84
39162,14,Thomas High School,Charter,1635,1043130,39162,Derek Weeks,M,12th,94,77
39163,14,Thomas High School,Charter,1635,1043130,39163,John Reese,M,11th,90,75
39164,14,Thomas High School,Charter,1635,1043130,39164,Joseph Anthony,M,9th,97,76
39165,14,Thomas High School,Charter,1635,1043130,39165,Donna Howard,F,12th,99,90
39166,14,Thomas High School,Charter,1635,1043130,39166,Dawn Bell,F,10th,95,70
39167,14,Thomas High School,Charter,1635,1043130,39167,Rebecca Tanner,F,9th,73,84
39168,14,Thomas High School,Charter,1635,1043130,39168,Desiree Kidd,F,10th,99,90
39169,14,Thomas High School,Charter,1635,1043130,39169,Carolyn Jackson,F,11th,95,75

In [26]:
passmath2=passmath["school_name"].value_counts()
#passmath2=passmath["school_name"].value_counts()/passmath["size"].unique()
#passmath2
passmath2

Bailey High School       3318
Johnson High School      3145
Hernandez High School    3094
Rodriguez High School    2654
Wilson High School       2143
Figueroa High School     1946
Huang High School        1916
Ford High School         1871
Cabrera High School      1749
Wright High School       1680
Shelton High School      1653
Thomas High School       1525
Griffin High School      1371
Pena High School          910
Holden High School        395
Name: school_name, dtype: int64

In [27]:
passmat3=passmath.groupby("school_name")["size"].unique()
passmat3

school_name
Bailey High School       [4976]
Cabrera High School      [1858]
Figueroa High School     [2949]
Ford High School         [2739]
Griffin High School      [1468]
Hernandez High School    [4635]
Holden High School        [427]
Huang High School        [2917]
Johnson High School      [4761]
Pena High School          [962]
Rodriguez High School    [3999]
Shelton High School      [1761]
Thomas High School       [1635]
Wilson High School       [2283]
Wright High School       [1800]
Name: size, dtype: object

In [28]:
passmatvf=(passmath2/passmat3*100)
passmatvf

Bailey High School       [66.68006430868168]
Cabrera High School       [94.1334768568353]
Figueroa High School     [65.98847066802306]
Ford High School          [68.3096020445418]
Griffin High School      [93.39237057220708]
Hernandez High School     [66.7529665587918]
Holden High School       [92.50585480093677]
Huang High School        [65.68392183750429]
Johnson High School       [66.0575509346776]
Pena High School          [94.5945945945946]
Rodriguez High School    [66.36659164791197]
Shelton High School       [93.8671209540034]
Thomas High School       [93.27217125382263]
Wilson High School        [93.8677179150241]
Wright High School       [93.33333333333333]
dtype: object

In [30]:
#% Passing READ
passread=datosc.loc[datosc["reading_score"]>=70]
passread

,School ID,school_name,type,size,budget,Student ID,student_name,gender,grade,reading_score,math_score
1,0,Huang High School,District,2917,1910635,1,Victor Smith,M,12th,94,61
2,0,Huang High School,District,2917,1910635,2,Kevin Rodriguez,M,12th,90,60
4,0,Huang High School,District,2917,1910635,4,Bonnie Ray,F,9th,97,84
5,0,Huang High School,District,2917,1910635,5,Bryan Miranda,M,9th,94,94
6,0,Huang High School,District,2917,1910635,6,Sheena Carter,F,11th,82,80
7,0,Huang High School,District,2917,1910635,7,Nicole Baker,F,12th,96,69
8,0,Huang High School,District,2917,1910635,8,Michael Roth,M,10th,95,87
9,0,Huang High School,District,2917,1910635,9,Matthew Greene,M,10th,96,84
10,0,Huang High School,District,2917,1910635,10,Andrew Alexander,M,10th,90,70
11,0,Huang High School,District,2917,1910635,11,Daniel Cooper,M,10th,78,77
13,0,Huang High School,District,2917,1910635,13,William Long,M,9th,71,79
14,0,Huang High School,District,2917,1910635,14,Tammy Hebert,F,10th,85,67
15,0,Huang High School,District,2917,1910635,15,Dr. Jordan Carson,M,11th,94,88
16,0,Huang High School,District,2917,1910635,16,Donald Zamora,M,9th,88,55
17,0,Huang High School,District,2917,1910635,17,Kimberly Santiago,F,9th,74,75
19,0,Huang High School,District,2917,1910635,19,Brandi Lyons,F,9th,89,80
20,0,Huang High School,District,2917,1910635,20,Lisa Davis,F,10th,91,89
21,0,Huang High School,District,2917,1910635,21,Kristen Lopez,F,10th,90,77
22,0,Huang High School,District,2917,1910635,22,Kimberly Stewart,F,11th,99,84
23,0,Huang High School,District,2917,1910635,23,Christopher Parker,M,9th,81,68
24,0,Huang High School,District,2917,1910635,24,Chelsea Griffith,F,11th,85,73
25,0,Huang High School,District,2917,1910635,25,Cesar Morris,M,9th,92,70
27,0,Huang High School,District,2917,1910635,27,Tracey Oconnor,F,10th,80,58
28,0,Huang High School,District,2917,1910635,28,Kelly James,F,11th,73,55
29,0,Huang High School,District,2917,1910635,29,Nicole Brown,F,12th,90,88
30,0,Huang High School,District,2917,1910635,30,Bobby Harris,M,9th,94,99
31,0,Huang High School,District,2917,1910635,31,Brian Fernandez,M,10th,97,65
32,0,Huang High School,District,2917,1910635,32,Candace Phelps,F,11th,93,90
33,0,Huang High School,District,2917,1910635,33,Amy Gonzalez,F,12th,95,68
35,0,Huang High School,District,2917,1910635,35,Benjamin Carlson,M,10th,99,61
...,...,...,...,...,...,...,...,...,...,...,...
39139,14,Thomas High School,Charter,1635,1043130,39139,Catherine Lee,F,9th,83,81
39140,14,Thomas High School,Charter,1635,1043130,39140,Cheyenne Hernandez,F,9th,76,99
39141,14,Thomas High School,Charter,1635,1043130,39141,Jonathan Sullivan,M,10th,86,93
39142,14,Thomas High School,Charter,1635,1043130,39142,Deborah Higgins DDS,F,10th,96,83
39143,14,Thomas High School,Charter,1635,1043130,39143,Steven Jackson,M,11th,71,93
39144,14,Thomas High School,Charter,1635,1043130,39144,Cristian Webster,M,12th,77,87
39145,14,Thomas High School,Charter,1635,1043130,39145,Audrey Fry,F,10th,94,74
39147,14,Thomas High School,Charter,1635,1043130,39147,Raymond Hawkins,M,10th,88,81
39148,14,Thomas High School,Charter,1635,1043130,39148,Christopher Wilson,M,10th,89,89
39149,14,Thomas High School,Charter,1635,1043130,39149,Glenda Fletcher,F,11th,82,93
39150,14,Thomas High School,Charter,1635,1043130,39150,Jennifer Hamilton,F,11th,80,75
39151,14,Thomas High School,Charter,1635,1043130,39151,Shannon Williams,F,10th,84,73
39152,14,Thomas High School,Charter,1635,1043130,39152,Lori Moore,F,9th,98,84
39153,14,Thomas High School,Charter,1635,1043130,39153,William Hubbard,M,9th,80,75
39154,14,Thomas High School,Charter,1635,1043130,39154,Bradley Johnson,M,12th,91,71
39155,14,Thomas High School,Charter,1635,1043130,39155,John Brooks,M,10th,92,98
39156,14,Thomas High School,Charter,1635,1043130,39156,Stephanie Contreras,F,11th,79,95
39157,14,Thomas High School,Charter,1635,1043130,39157,Kristen Gonzalez,F,9th,79,94
39158,14,Thomas High School,Charter,1635,1043130,39158,Kari Holloway,F,10th,87,90
39159,14,Thomas High School,Charter,1635,1043130,39159,Kimberly Cabrera,F,11th,85,72
39160,14,Thomas High School,Charter,1635,1043130,39160,Katie Weaver,F,11th,89,86
39161,14,Thomas High School,Charter,1635,1043130,39161,April Reyes,F,10th,70,84
39162,14,Thomas High School,Charter,1635,1043130,39162,Derek Weeks,M,12th,94,77
39163,14,Thomas High School,Charter,1635,1043130,39163,John Reese,M,11th,90,75
39164,14,Thomas High School,Charter,1635,1043130,39164,Joseph Anthony,M,9th,97,76
39165,14,Thomas High School,Charter,1635,1043130,39165,Donna Howard,F,12th,99,90
39166,14,Thomas High School,Charter,1635,1043130,39166,Dawn Bell,F,10th,95,70
39167,14,Thomas High School,Charter,1635,1043130,39167,Rebecca Tanner,F,9th,73,84
39168,14,Thomas High School,Charter,1635,1043130,39168,Desiree Kidd,F,10th,99,90
39169,14,Thomas High School,Charter,1635,1043130,39169,Carolyn Jackson,F,11th,95,75

In [31]:
passreadf=passread["school_name"].value_counts()/passread.groupby("school_name")["size"].unique()*100
passreadf

Bailey High School       [81.93327974276528]
Cabrera High School      [97.03982777179763]
Figueroa High School     [80.73923363852154]
Ford High School         [79.29901423877328]
Griffin High School      [97.13896457765668]
Hernandez High School    [80.86299892125135]
Holden High School       [96.25292740046838]
Huang High School        [81.31642098045938]
Johnson High School       [81.2224322621298]
Pena High School         [95.94594594594594]
Rodriguez High School    [80.22005501375344]
Shelton High School      [95.85462805224304]
Thomas High School       [97.30886850152906]
Wilson High School       [96.53964082347788]
Wright High School       [96.61111111111111]
dtype: object

In [33]:
Overall=(passmatvf+passreadf)/2
Overall

Bailey High School       [74.30667202572349]
Cabrera High School      [95.58665231431647]
Figueroa High School     [73.36385215327229]
Ford High School         [73.80430814165754]
Griffin High School      [95.26566757493188]
Hernandez High School    [73.80798274002157]
Holden High School       [94.37939110070258]
Huang High School        [73.50017140898183]
Johnson High School       [73.6399915984037]
Pena High School         [95.27027027027026]
Rodriguez High School     [73.2933233308327]
Shelton High School      [94.86087450312323]
Thomas High School       [95.29051987767585]
Wilson High School       [95.20367936925099]
Wright High School       [94.97222222222223]
dtype: object

# School Summary

In [36]:
sumschool={
    'School Type': Type,
    'Total Students':Students,
    'Total School Budget': Schoolbud,
    'Per Student Budget': PSB2,
    'Average Math Score': AMS,
    'Average Reading Score': ARS,
    '% Passing Math': passmatvf,
    '% Passing Reading': passreadf,
    '% Overall Passing Rate': Overall,}

In [37]:
dfschool_summary = pd.DataFrame(sumschool)
dfschool_summary

,School Type,Total Students,Total School Budget,Per Student Budget,Average Math Score,Average Reading Score,% Passing Math,% Passing Reading,% Overall Passing Rate
school_name,,,,,,,,,
Bailey High School,[District],[4976],[3124928],[628.0],[77.04843247588424],[81.03396302250803],[66.68006430868168],[81.93327974276528],[74.30667202572349]
Cabrera High School,[Charter],[1858],[1081356],[582.0],[83.06189451022605],[83.97578040904197],[94.1334768568353],[97.03982777179763],[95.58665231431647]
Figueroa High School,[District],[2949],[1884411],[639.0],[76.71176670057646],[81.15801966768396],[65.98847066802306],[80.73923363852154],[73.36385215327229]
Ford High School,[District],[2739],[1763916],[644.0],[77.10259218692954],[80.74625775830594],[68.3096020445418],[79.29901423877328],[73.80430814165754]
Griffin High School,[Charter],[1468],[917500],[625.0],[83.35149863760218],[83.816757493188],[93.39237057220708],[97.13896457765668],[95.26566757493188]
Hernandez High School,[District],[4635],[3022020],[652.0],[77.28975188781014],[80.9344120819849],[66.7529665587918],[80.86299892125135],[73.80798274002157]
Holden High School,[Charter],[427],[248087],[581.0],[83.80327868852459],[83.81498829039812],[92.50585480093677],[96.25292740046838],[94.37939110070258]
Huang High School,[District],[2917],[1910635],[655.0],[76.62941378128214],[81.18272197463148],[65.68392183750429],[81.31642098045938],[73.50017140898183]
Johnson High School,[District],[4761],[3094650],[650.0],[77.07246376811594],[80.96639361478681],[66.0575509346776],[81.2224322621298],[73.6399915984037]
Pena High School,[Charter],[962],[585858],[609.0],[83.83991683991684],[84.04469854469855],[94.5945945945946],[95.94594594594594],[95.27027027027026]
Rodriguez High School,[District],[3999],[2547363],[637.0],[76.84271067766942],[80.74468617154288],[66.36659164791197],[80.22005501375344],[73.2933233308327]
Shelton High School,[Charter],[1761],[1056600],[600.0],[83.3594548551959],[83.72572402044293],[93.8671209540034],[95.85462805224304],[94.86087450312323]
Thomas High School,[Charter],[1635],[1043130],[638.0],[83.4183486238532],[83.84892966360856],[93.27217125382263],[97.30886850152906],[95.29051987767585]
Wilson High School,[Charter],[2283],[1319574],[578.0],[83.2742006132282],[83.98948751642575],[93.8677179150241],[96.53964082347788],[95.20367936925099]
Wright High School,[Charter],[1800],[1049400],[583.0],[83.68222222222222],[83.955],[93.33333333333333],[96.61111111111111],[94.97222222222223]

# Top Performing Schools (By Passing Rate)

In [39]:
#Sort and display the top five schools in overall passing rate
topperforming_schools = dfschool_summary.sort_values(by='% Overall Passing Rate',ascending=False)
topperforming_schools.head()

,School Type,Total Students,Total School Budget,Per Student Budget,Average Math Score,Average Reading Score,% Passing Math,% Passing Reading,% Overall Passing Rate
school_name,,,,,,,,,
Cabrera High School,[Charter],[1858],[1081356],[582.0],[83.06189451022605],[83.97578040904197],[94.1334768568353],[97.03982777179763],[95.58665231431647]
Thomas High School,[Charter],[1635],[1043130],[638.0],[83.4183486238532],[83.84892966360856],[93.27217125382263],[97.30886850152906],[95.29051987767585]
Pena High School,[Charter],[962],[585858],[609.0],[83.83991683991684],[84.04469854469855],[94.5945945945946],[95.94594594594594],[95.27027027027026]
Griffin High School,[Charter],[1468],[917500],[625.0],[83.35149863760218],[83.816757493188],[93.39237057220708],[97.13896457765668],[95.26566757493188]
Wilson High School,[Charter],[2283],[1319574],[578.0],[83.2742006132282],[83.98948751642575],[93.8677179150241],[96.53964082347788],[95.20367936925099]

In [41]:
# Sort and display the five worst-performing schools
worstperforming_schools = dfschool_summary.sort_values(by='% Overall Passing Rate')
worstperforming_schools.head()

,School Type,Total Students,Total School Budget,Per Student Budget,Average Math Score,Average Reading Score,% Passing Math,% Passing Reading,% Overall Passing Rate
school_name,,,,,,,,,
Rodriguez High School,[District],[3999],[2547363],[637.0],[76.84271067766942],[80.74468617154288],[66.36659164791197],[80.22005501375344],[73.2933233308327]
Figueroa High School,[District],[2949],[1884411],[639.0],[76.71176670057646],[81.15801966768396],[65.98847066802306],[80.73923363852154],[73.36385215327229]
Huang High School,[District],[2917],[1910635],[655.0],[76.62941378128214],[81.18272197463148],[65.68392183750429],[81.31642098045938],[73.50017140898183]
Johnson High School,[District],[4761],[3094650],[650.0],[77.07246376811594],[80.96639361478681],[66.0575509346776],[81.2224322621298],[73.6399915984037]
Ford High School,[District],[2739],[1763916],[644.0],[77.10259218692954],[80.74625775830594],[68.3096020445418],[79.29901423877328],[73.80430814165754]

#  Scores by Grade

In [42]:
#Math Scores by Grade
#Create a pandas series for each grade. Hint: use a conditional statement.
nineg=datosc.loc[datosc["grade"]=="9th",:]
nineg

,School ID,school_name,type,size,budget,Student ID,student_name,gender,grade,reading_score,math_score
0,0,Huang High School,District,2917,1910635,0,Paul Bradley,M,9th,66,79
4,0,Huang High School,District,2917,1910635,4,Bonnie Ray,F,9th,97,84
5,0,Huang High School,District,2917,1910635,5,Bryan Miranda,M,9th,94,94
12,0,Huang High School,District,2917,1910635,12,Brittney Walker,F,9th,64,79
13,0,Huang High School,District,2917,1910635,13,William Long,M,9th,71,79
16,0,Huang High School,District,2917,1910635,16,Donald Zamora,M,9th,88,55
17,0,Huang High School,District,2917,1910635,17,Kimberly Santiago,F,9th,74,75
18,0,Huang High School,District,2917,1910635,18,Kevin Stevens,M,9th,64,69
19,0,Huang High School,District,2917,1910635,19,Brandi Lyons,F,9th,89,80
23,0,Huang High School,District,2917,1910635,23,Christopher Parker,M,9th,81,68
25,0,Huang High School,District,2917,1910635,25,Cesar Morris,M,9th,92,70
26,0,Huang High School,District,2917,1910635,26,Melanie Decker,F,9th,63,85
30,0,Huang High School,District,2917,1910635,30,Bobby Harris,M,9th,94,99
39,0,Huang High School,District,2917,1910635,39,Gregory Roberts,M,9th,80,61
40,0,Huang High School,District,2917,1910635,40,Matthew Mayer,M,9th,79,69
42,0,Huang High School,District,2917,1910635,42,John Carlson,M,9th,65,89
43,0,Huang High School,District,2917,1910635,43,Megan Roberts,F,9th,66,90
48,0,Huang High School,District,2917,1910635,48,Amy Perkins,F,9th,76,66
53,0,Huang High School,District,2917,1910635,53,Jon Smith,M,9th,96,69
54,0,Huang High School,District,2917,1910635,54,Tracey Yates,F,9th,83,68
57,0,Huang High School,District,2917,1910635,57,Madeline Snyder MD,F,9th,97,56
59,0,Huang High School,District,2917,1910635,59,Theresa Meyer,F,9th,88,70
60,0,Huang High School,District,2917,1910635,60,Jared Wood,M,9th,63,89
61,0,Huang High School,District,2917,1910635,61,Eric Maynard,M,9th,64,95
76,0,Huang High School,District,2917,1910635,76,Erin Liu,F,9th,78,76
79,0,Huang High School,District,2917,1910635,79,Elizabeth Mckinney,F,9th,74,81
90,0,Huang High School,District,2917,1910635,90,Ronald Garcia,M,9th,99,86
92,0,Huang High School,District,2917,1910635,92,Ryan Stokes,M,9th,75,72
96,0,Huang High School,District,2917,1910635,96,Jessica Smith,F,9th,77,72
104,0,Huang High School,District,2917,1910635,104,Michael Savage,M,9th,75,66
...,...,...,...,...,...,...,...,...,...,...,...
39083,14,Thomas High School,Charter,1635,1043130,39083,Gloria Wilson,F,9th,90,73
39084,14,Thomas High School,Charter,1635,1043130,39084,Angela Daniels,F,9th,86,91
39085,14,Thomas High School,Charter,1635,1043130,39085,Marcus Morgan,M,9th,91,88
39087,14,Thomas High School,Charter,1635,1043130,39087,Lisa Kennedy,F,9th,94,68
39089,14,Thomas High School,Charter,1635,1043130,39089,Lindsey Thompson,F,9th,96,79
39090,14,Thomas High School,Charter,1635,1043130,39090,Lori Dickson,F,9th,81,83
39092,14,Thomas High School,Charter,1635,1043130,39092,Joseph Burgess,M,9th,90,96
39093,14,Thomas High School,Charter,1635,1043130,39093,Antonio Kirk,M,9th,73,74
39102,14,Thomas High School,Charter,1635,1043130,39102,Jennifer White,F,9th,85,94
39103,14,Thomas High School,Charter,1635,1043130,39103,Carrie Stewart,F,9th,83,91
39105,14,Thomas High School,Charter,1635,1043130,39105,Dr. Kimberly Page,F,9th,88,85
39107,14,Thomas High School,Charter,1635,1043130,39107,Stacy Wells,F,9th,72,81
39111,14,Thomas High School,Charter,1635,1043130,39111,Mary Coffey,F,9th,93,89
39117,14,Thomas High School,Charter,1635,1043130,39117,Daniel Best,M,9th,86,98
39123,14,Thomas High School,Charter,1635,1043130,39123,Andrew Merritt,M,9th,71,82
39124,14,Thomas High School,Charter,1635,1043130,39124,Susan Simon,F,9th,71,98
39127,14,Thomas High School,Charter,1635,1043130,39127,Robert Wood,M,9th,97,98
39128,14,Thomas High School,Charter,1635,1043130,39128,Jonathan Mueller,M,9th,82,98
39131,14,Thomas High School,Charter,1635,1043130,39131,Brian Williams,M,9th,72,86
39132,14,Thomas High School,Charter,1635,1043130,39132,Shawn Hayden,M,9th,69,78
39135,14,Thomas High School,Charter,1635,1043130,39135,Laura Webster,F,9th,78,81
39138,14,Thomas High School,Charter,1635,1043130,39138,Monica Hampton,F,9th,94,94
39139,14,Thomas High School,Charter,1635,1043130,39139,Catherine Lee,F,9th,83,81
39140,14,Thomas High School,Charter,1635,1043130,39140,Cheyenne Hernandez,F,9th,76,99
39146,14,Thomas High School,Charter,1635,1043130,39146,Michael Carroll,M,9th,69,95
39152,14,Thomas High School,Charter,1635,1043130,39152,Lori Moore,F,9th,98,84
39153,14,Thomas High School,Charter,1635,1043130,39153,William Hubbard,M,9th,80,75
39157,14,Thomas High School,Charter,1635,1043130,39157,Kristen Gonzalez,F,9th,79,94
39164,14,Thomas High School,Charter,1635,1043130,39164,Joseph Anthony,M,9th,97,76
39167,14,Thomas High School,Charter,1635,1043130,39167,Rebecca Tanner,F,9th,73,84

In [43]:
#READING
nine=nineg.groupby("school_name")["reading_score"].mean()
nine

school_name
Bailey High School       81.303155
Cabrera High School      83.676136
Figueroa High School     81.198598
Ford High School         80.632653
Griffin High School      83.369193
Hernandez High School    80.866860
Holden High School       83.677165
Huang High School        81.290284
Johnson High School      81.260714
Pena High School         83.807273
Rodriguez High School    80.993127
Shelton High School      84.122642
Thomas High School       83.728850
Wilson High School       83.939778
Wright High School       83.833333
Name: reading_score, dtype: float64

In [44]:
teng=datosc.loc[datosc["grade"]=="10th",:]
teng

,School ID,school_name,type,size,budget,Student ID,student_name,gender,grade,reading_score,math_score
8,0,Huang High School,District,2917,1910635,8,Michael Roth,M,10th,95,87
9,0,Huang High School,District,2917,1910635,9,Matthew Greene,M,10th,96,84
10,0,Huang High School,District,2917,1910635,10,Andrew Alexander,M,10th,90,70
11,0,Huang High School,District,2917,1910635,11,Daniel Cooper,M,10th,78,77
14,0,Huang High School,District,2917,1910635,14,Tammy Hebert,F,10th,85,67
20,0,Huang High School,District,2917,1910635,20,Lisa Davis,F,10th,91,89
21,0,Huang High School,District,2917,1910635,21,Kristen Lopez,F,10th,90,77
27,0,Huang High School,District,2917,1910635,27,Tracey Oconnor,F,10th,80,58
31,0,Huang High School,District,2917,1910635,31,Brian Fernandez,M,10th,97,65
35,0,Huang High School,District,2917,1910635,35,Benjamin Carlson,M,10th,99,61
36,0,Huang High School,District,2917,1910635,36,Kevin Bailey,M,10th,76,76
37,0,Huang High School,District,2917,1910635,37,Jesse Newton,M,10th,63,66
44,0,Huang High School,District,2917,1910635,44,Debra Flores,F,10th,75,66
49,0,Huang High School,District,2917,1910635,49,Natalie Mitchell,F,10th,73,93
50,0,Huang High School,District,2917,1910635,50,Tiffany Gutierrez,F,10th,82,95
66,0,Huang High School,District,2917,1910635,66,Mr. Dylan Taylor MD,M,10th,77,93
71,0,Huang High School,District,2917,1910635,71,Breanna Taylor,F,10th,93,68
73,0,Huang High School,District,2917,1910635,73,Kyle Martin,M,10th,72,94
74,0,Huang High School,District,2917,1910635,74,Dr. Scott Gill,M,10th,85,85
75,0,Huang High School,District,2917,1910635,75,Lisa Long,F,10th,87,62
80,0,Huang High School,District,2917,1910635,80,Jessica Bailey,F,10th,67,70
84,0,Huang High School,District,2917,1910635,84,Joseph Butler,M,10th,77,63
85,0,Huang High School,District,2917,1910635,85,Tina Lynch,F,10th,94,60
86,0,Huang High School,District,2917,1910635,86,Leah Benitez,F,10th,93,84
87,0,Huang High School,District,2917,1910635,87,Elizabeth Parker,F,10th,85,56
88,0,Huang High School,District,2917,1910635,88,Melissa Hunter,F,10th,90,70
91,0,Huang High School,District,2917,1910635,91,Mark Cherry,M,10th,96,98
93,0,Huang High School,District,2917,1910635,93,Isaiah Maldonado,M,10th,84,91
98,0,Huang High School,District,2917,1910635,98,Virginia Ramirez MD,F,10th,99,89
99,0,Huang High School,District,2917,1910635,99,Marc Hernandez,M,10th,87,63
...,...,...,...,...,...,...,...,...,...,...,...
39049,14,Thomas High School,Charter,1635,1043130,39049,Preston Davis,M,10th,98,84
39052,14,Thomas High School,Charter,1635,1043130,39052,Larry Robinson,M,10th,74,88
39057,14,Thomas High School,Charter,1635,1043130,39057,Michael Strong,M,10th,78,91
39066,14,Thomas High School,Charter,1635,1043130,39066,Derrick Alexander,M,10th,88,89
39073,14,Thomas High School,Charter,1635,1043130,39073,Susan Gates,F,10th,71,80
39074,14,Thomas High School,Charter,1635,1043130,39074,Jason Lawrence,M,10th,96,69
39079,14,Thomas High School,Charter,1635,1043130,39079,Sandy Johns,F,10th,88,87
39082,14,Thomas High School,Charter,1635,1043130,39082,Jennifer Harris,F,10th,92,98
39086,14,Thomas High School,Charter,1635,1043130,39086,Joanna Allen,F,10th,74,75
39088,14,Thomas High School,Charter,1635,1043130,39088,Joseph Stewart,M,10th,75,83
39091,14,Thomas High School,Charter,1635,1043130,39091,Jeremy Edwards,M,10th,91,98
39098,14,Thomas High School,Charter,1635,1043130,39098,Nancy Silva,F,10th,73,94
39101,14,Thomas High School,Charter,1635,1043130,39101,Tammy Torres,F,10th,83,68
39114,14,Thomas High School,Charter,1635,1043130,39114,Gregory Taylor,M,10th,99,77
39119,14,Thomas High School,Charter,1635,1043130,39119,Katherine Harrison,F,10th,86,94
39121,14,Thomas High School,Charter,1635,1043130,39121,Stephanie Wilson,F,10th,94,94
39122,14,Thomas High School,Charter,1635,1043130,39122,Samantha Johnson,F,10th,80,68
39126,14,Thomas High School,Charter,1635,1043130,39126,Samuel Casey,M,10th,97,85
39129,14,Thomas High School,Charter,1635,1043130,39129,Diane Miller,F,10th,81,91
39141,14,Thomas High School,Charter,1635,1043130,39141,Jonathan Sullivan,M,10th,86,93
39142,14,Thomas High School,Charter,1635,1043130,39142,Deborah Higgins DDS,F,10th,96,83
39145,14,Thomas High School,Charter,1635,1043130,39145,Audrey Fry,F,10th,94,74
39147,14,Thomas High School,Charter,1635,1043130,39147,Raymond Hawkins,M,10th,88,81
39148,14,Thomas High School,Charter,1635,1043130,39148,Christopher Wilson,M,10th,89,89
39151,14,Thomas High School,Charter,1635,1043130,39151,Shannon Williams,F,10th,84,73
39155,14,Thomas High School,Charter,1635,1043130,39155,John Brooks,M,10th,92,98
39158,14,Thomas High School,Charter,1635,1043130,39158,Kari Holloway,F,10th,87,90
39161,14,Thomas High School,Charter,1635,1043130,39161,April Reyes,F,10th,70,84
39166,14,Thomas High School,Charter,1635,1043130,39166,Dawn Bell,F,10th,95,70
39168,14,Thomas High School,Charter,1635,1043130,39168,Desiree Kidd,F,10th,99,90

In [45]:
teng2=teng.groupby("school_name")["reading_score"].mean()
teng2

school_name
Bailey High School       80.907183
Cabrera High School      84.253219
Figueroa High School     81.408912
Ford High School         81.262712
Griffin High School      83.706897
Hernandez High School    80.660147
Holden High School       83.324561
Huang High School        81.512386
Johnson High School      80.773431
Pena High School         83.612000
Rodriguez High School    80.629808
Shelton High School      83.441964
Thomas High School       84.254157
Wilson High School       84.021452
Wright High School       83.812757
Name: reading_score, dtype: float64

In [48]:
eleveng=datosc.loc[datosc["grade"]=="11th",:]

In [49]:
eleven=eleveng.groupby("school_name")["reading_score"].mean()
eleven

school_name
Bailey High School       80.945643
Cabrera High School      83.788382
Figueroa High School     80.640339
Ford High School         80.403642
Griffin High School      84.288089
Hernandez High School    81.396140
Holden High School       83.815534
Huang High School        81.417476
Johnson High School      80.616027
Pena High School         84.335938
Rodriguez High School    80.864811
Shelton High School      84.373786
Thomas High School       83.585542
Wilson High School       83.764608
Wright High School       84.156322
Name: reading_score, dtype: float64

In [50]:
twelveg=datosc.loc[datosc["grade"]=="12th",:]

In [51]:
twelven=twelveg.groupby("school_name")["reading_score"].mean()
twelven

school_name
Bailey High School       80.912451
Cabrera High School      84.287958
Figueroa High School     81.384863
Ford High School         80.662338
Griffin High School      84.013699
Hernandez High School    80.857143
Holden High School       84.698795
Huang High School        80.305983
Johnson High School      81.227564
Pena High School         84.591160
Rodriguez High School    80.376426
Shelton High School      82.781671
Thomas High School       83.831361
Wilson High School       84.317673
Wright High School       84.073171
Name: reading_score, dtype: float64

# Reading Score by Grade

In [62]:
#Combine the series into a dataframe
Read={
    '9th':nine,
    '10th':teng2,
    '11th':eleven,
    '12th':twelven,
    }

In [63]:
dfread= pd.DataFrame(Read)
dfread

                             9th       10th       11th       12th
school_name
Bailey High School     81.303155  80.907183  80.945643  80.912451
Cabrera High School    83.676136  84.253219  83.788382  84.287958
Figueroa High School   81.198598  81.408912  80.640339  81.384863
Ford High School       80.632653  81.262712  80.403642  80.662338
Griffin High School    83.369193  83.706897  84.288089  84.013699
Hernandez High School  80.866860  80.660147  81.396140  80.857143
Holden High School     83.677165  83.324561  83.815534  84.698795
Huang High School      81.290284  81.512386  81.417476  80.305983
Johnson High School    81.260714  80.773431  80.616027  81.227564
Pena High School       83.807273  83.612000  84.335938  84.591160
Rodriguez High School  80.993127  80.629808  80.864811  80.376426
Shelton High School    84.122642  83.441964  84.373786  82.781671
Thomas High School     83.728850  84.254157  83.585542  83.831361
Wilson High School     83.939778  84.021452  83.764608  84.317673
Wright High School     83.833333  83.812757  84.156322  84.073171

In [57]:
##math
nineg2=datosc.loc[datosc["grade"]=="9th",:]
nineg2

,School ID,school_name,type,size,budget,Student ID,student_name,gender,grade,reading_score,math_score
0,0,Huang High School,District,2917,1910635,0,Paul Bradley,M,9th,66,79
4,0,Huang High School,District,2917,1910635,4,Bonnie Ray,F,9th,97,84
5,0,Huang High School,District,2917,1910635,5,Bryan Miranda,M,9th,94,94
12,0,Huang High School,District,2917,1910635,12,Brittney Walker,F,9th,64,79
13,0,Huang High School,District,2917,1910635,13,William Long,M,9th,71,79
16,0,Huang High School,District,2917,1910635,16,Donald Zamora,M,9th,88,55
17,0,Huang High School,District,2917,1910635,17,Kimberly Santiago,F,9th,74,75
18,0,Huang High School,District,2917,1910635,18,Kevin Stevens,M,9th,64,69
19,0,Huang High School,District,2917,1910635,19,Brandi Lyons,F,9th,89,80
23,0,Huang High School,District,2917,1910635,23,Christopher Parker,M,9th,81,68
25,0,Huang High School,District,2917,1910635,25,Cesar Morris,M,9th,92,70
26,0,Huang High School,District,2917,1910635,26,Melanie Decker,F,9th,63,85
30,0,Huang High School,District,2917,1910635,30,Bobby Harris,M,9th,94,99
39,0,Huang High School,District,2917,1910635,39,Gregory Roberts,M,9th,80,61
40,0,Huang High School,District,2917,1910635,40,Matthew Mayer,M,9th,79,69
42,0,Huang High School,District,2917,1910635,42,John Carlson,M,9th,65,89
43,0,Huang High School,District,2917,1910635,43,Megan Roberts,F,9th,66,90
48,0,Huang High School,District,2917,1910635,48,Amy Perkins,F,9th,76,66
53,0,Huang High School,District,2917,1910635,53,Jon Smith,M,9th,96,69
54,0,Huang High School,District,2917,1910635,54,Tracey Yates,F,9th,83,68
57,0,Huang High School,District,2917,1910635,57,Madeline Snyder MD,F,9th,97,56
59,0,Huang High School,District,2917,1910635,59,Theresa Meyer,F,9th,88,70
60,0,Huang High School,District,2917,1910635,60,Jared Wood,M,9th,63,89
61,0,Huang High School,District,2917,1910635,61,Eric Maynard,M,9th,64,95
76,0,Huang High School,District,2917,1910635,76,Erin Liu,F,9th,78,76
79,0,Huang High School,District,2917,1910635,79,Elizabeth Mckinney,F,9th,74,81
90,0,Huang High School,District,2917,1910635,90,Ronald Garcia,M,9th,99,86
92,0,Huang High School,District,2917,1910635,92,Ryan Stokes,M,9th,75,72
96,0,Huang High School,District,2917,1910635,96,Jessica Smith,F,9th,77,72
104,0,Huang High School,District,2917,1910635,104,Michael Savage,M,9th,75,66
...,...,...,...,...,...,...,...,...,...,...,...
39083,14,Thomas High School,Charter,1635,1043130,39083,Gloria Wilson,F,9th,90,73
39084,14,Thomas High School,Charter,1635,1043130,39084,Angela Daniels,F,9th,86,91
39085,14,Thomas High School,Charter,1635,1043130,39085,Marcus Morgan,M,9th,91,88
39087,14,Thomas High School,Charter,1635,1043130,39087,Lisa Kennedy,F,9th,94,68
39089,14,Thomas High School,Charter,1635,1043130,39089,Lindsey Thompson,F,9th,96,79
39090,14,Thomas High School,Charter,1635,1043130,39090,Lori Dickson,F,9th,81,83
39092,14,Thomas High School,Charter,1635,1043130,39092,Joseph Burgess,M,9th,90,96
39093,14,Thomas High School,Charter,1635,1043130,39093,Antonio Kirk,M,9th,73,74
39102,14,Thomas High School,Charter,1635,1043130,39102,Jennifer White,F,9th,85,94
39103,14,Thomas High School,Charter,1635,1043130,39103,Carrie Stewart,F,9th,83,91
39105,14,Thomas High School,Charter,1635,1043130,39105,Dr. Kimberly Page,F,9th,88,85
39107,14,Thomas High School,Charter,1635,1043130,39107,Stacy Wells,F,9th,72,81
39111,14,Thomas High School,Charter,1635,1043130,39111,Mary Coffey,F,9th,93,89
39117,14,Thomas High School,Charter,1635,1043130,39117,Daniel Best,M,9th,86,98
39123,14,Thomas High School,Charter,1635,1043130,39123,Andrew Merritt,M,9th,71,82
39124,14,Thomas High School,Charter,1635,1043130,39124,Susan Simon,F,9th,71,98
39127,14,Thomas High School,Charter,1635,1043130,39127,Robert Wood,M,9th,97,98
39128,14,Thomas High School,Charter,1635,1043130,39128,Jonathan Mueller,M,9th,82,98
39131,14,Thomas High School,Charter,1635,1043130,39131,Brian Williams,M,9th,72,86
39132,14,Thomas High School,Charter,1635,1043130,39132,Shawn Hayden,M,9th,69,78
39135,14,Thomas High School,Charter,1635,1043130,39135,Laura Webster,F,9th,78,81
39138,14,Thomas High School,Charter,1635,1043130,39138,Monica Hampton,F,9th,94,94
39139,14,Thomas High School,Charter,1635,1043130,39139,Catherine Lee,F,9th,83,81
39140,14,Thomas High School,Charter,1635,1043130,39140,Cheyenne Hernandez,F,9th,76,99
39146,14,Thomas High School,Charter,1635,1043130,39146,Michael Carroll,M,9th,69,95
39152,14,Thomas High School,Charter,1635,1043130,39152,Lori Moore,F,9th,98,84
39153,14,Thomas High School,Charter,1635,1043130,39153,William Hubbard,M,9th,80,75
39157,14,Thomas High School,Charter,1635,1043130,39157,Kristen Gonzalez,F,9th,79,94
39164,14,Thomas High School,Charter,1635,1043130,39164,Joseph Anthony,M,9th,97,76
39167,14,Thomas High School,Charter,1635,1043130,39167,Rebecca Tanner,F,9th,73,84

In [58]:
ninem=nineg2.groupby("school_name")["math_score"].mean()
ninem

school_name
Bailey High School       77.083676
Cabrera High School      83.094697
Figueroa High School     76.403037
Ford High School         77.361345
Griffin High School      82.044010
Hernandez High School    77.438495
Holden High School       83.787402
Huang High School        77.027251
Johnson High School      77.187857
Pena High School         83.625455
Rodriguez High School    76.859966
Shelton High School      83.420755
Thomas High School       83.590022
Wilson High School       83.085578
Wright High School       83.264706
Name: math_score, dtype: float64

In [59]:
tengm=teng.groupby("school_name")["math_score"].mean()
tengm

school_name
Bailey High School       76.996772
Cabrera High School      83.154506
Figueroa High School     76.539974
Ford High School         77.672316
Griffin High School      84.229064
Hernandez High School    77.337408
Holden High School       83.429825
Huang High School        75.908735
Johnson High School      76.691117
Pena High School         83.372000
Rodriguez High School    76.612500
Shelton High School      82.917411
Thomas High School       83.087886
Wilson High School       83.724422
Wright High School       84.010288
Name: math_score, dtype: float64

In [60]:
elevenm=eleveng.groupby("school_name")["math_score"].mean()
elevenm

school_name
Bailey High School       77.515588
Cabrera High School      82.765560
Figueroa High School     76.884344
Ford High School         76.918058
Griffin High School      83.842105
Hernandez High School    77.136029
Holden High School       85.000000
Huang High School        76.446602
Johnson High School      77.491653
Pena High School         84.328125
Rodriguez High School    76.395626
Shelton High School      83.383495
Thomas High School       83.498795
Wilson High School       83.195326
Wright High School       83.836782
Name: math_score, dtype: float64

In [61]:
twelvem=twelveg.groupby("school_name")["math_score"].mean()
twelvem

school_name
Bailey High School       76.492218
Cabrera High School      83.277487
Figueroa High School     77.151369
Ford High School         76.179963
Griffin High School      83.356164
Hernandez High School    77.186567
Holden High School       82.855422
Huang High School        77.225641
Johnson High School      76.863248
Pena High School         84.121547
Rodriguez High School    77.690748
Shelton High School      83.778976
Thomas High School       83.497041
Wilson High School       83.035794
Wright High School       83.644986
Name: math_score, dtype: float64

# Math Scores by Grade

In [64]:
#Combine the series into a dataframe
Math={
    '9th':ninem,
    '10th':tengm,
    '11th':elevenm,
    '12th':twelvem,
    }

In [65]:
dfmath= pd.DataFrame(Math)
dfmath

                             9th       10th       11th       12th
school_name
Bailey High School     77.083676  76.996772  77.515588  76.492218
Cabrera High School    83.094697  83.154506  82.765560  83.277487
Figueroa High School   76.403037  76.539974  76.884344  77.151369
Ford High School       77.361345  77.672316  76.918058  76.179963
Griffin High School    82.044010  84.229064  83.842105  83.356164
Hernandez High School  77.438495  77.337408  77.136029  77.186567
Holden High School     83.787402  83.429825  85.000000  82.855422
Huang High School      77.027251  75.908735  76.446602  77.225641
Johnson High School    77.187857  76.691117  77.491653  76.863248
Pena High School       83.625455  83.372000  84.328125  84.121547
Rodriguez High School  76.859966  76.612500  76.395626  77.690748
Shelton High School    83.420755  82.917411  83.383495  83.778976
Thomas High School     83.590022  83.087886  83.498795  83.497041
Wilson High School     83.085578  83.724422  83.195326  83.035794
Wright High School     83.264706  84.010288  83.836782  83.644986

# Scores by School Spending

In [66]:
# Bins
spending_bins = [0, 585, 615, 645, 675]
groups= ["<$585", "$585-615", "$615-645", "$645-675"]

In [67]:
spending = dfschool_summary.loc[:,['Average Math Score','Average Reading Score','% Passing Math','% Passing Reading','% Overall Passing Rate',]]

In [68]:
spending

,Average Math Score,Average Reading Score,% Passing Math,% Passing Reading,% Overall Passing Rate
school_name,,,,,
Bailey High School,[77.04843247588424],[81.03396302250803],[66.68006430868168],[81.93327974276528],[74.30667202572349]
Cabrera High School,[83.06189451022605],[83.97578040904197],[94.1334768568353],[97.03982777179763],[95.58665231431647]
Figueroa High School,[76.71176670057646],[81.15801966768396],[65.98847066802306],[80.73923363852154],[73.36385215327229]
Ford High School,[77.10259218692954],[80.74625775830594],[68.3096020445418],[79.29901423877328],[73.80430814165754]
Griffin High School,[83.35149863760218],[83.816757493188],[93.39237057220708],[97.13896457765668],[95.26566757493188]
Hernandez High School,[77.28975188781014],[80.9344120819849],[66.7529665587918],[80.86299892125135],[73.80798274002157]
Holden High School,[83.80327868852459],[83.81498829039812],[92.50585480093677],[96.25292740046838],[94.37939110070258]
Huang High School,[76.62941378128214],[81.18272197463148],[65.68392183750429],[81.31642098045938],[73.50017140898183]
Johnson High School,[77.07246376811594],[80.96639361478681],[66.0575509346776],[81.2224322621298],[73.6399915984037]
Pena High School,[83.83991683991684],[84.04469854469855],[94.5945945945946],[95.94594594594594],[95.27027027027026]
Rodriguez High School,[76.84271067766942],[80.74468617154288],[66.36659164791197],[80.22005501375344],[73.2933233308327]
Shelton High School,[83.3594548551959],[83.72572402044293],[93.8671209540034],[95.85462805224304],[94.86087450312323]
Thomas High School,[83.4183486238532],[83.84892966360856],[93.27217125382263],[97.30886850152906],[95.29051987767585]
Wilson High School,[83.2742006132282],[83.98948751642575],[93.8677179150241],[96.53964082347788],[95.20367936925099]
Wright High School,[83.68222222222222],[83.955],[93.33333333333333],[96.61111111111111],[94.97222222222223]

In [75]:
spending['Spending Ranges (Per Student)']= pd.cut(dfschool_summary['Per Student Budget'],spending_bins,labels=groups)

In [103]:
spending

,Average Math Score,Average Reading Score,% Passing Math,% Passing Reading,% Overall Passing Rate
Spending Ranges (Per Student),,,,,
<$585,4,4,4,4,4
$585-615,2,2,2,2,2
$615-645,6,6,6,6,6
$645-675,3,3,3,3,3

In [100]:
spending2 =spending.groupby(["Spending Ranges (Per Student)"])["Average Math Score"].mean()
spending2

Spending Ranges (Per Student)
<$585       4
$585-615    2
$615-645    6
$645-675    3
Name: Average Math Score, dtype: int64

# Scores by School Size

In [79]:
#Samples
s_bins = [0, 1000, 2000, 5000]
group_sc = ["Small (<1000)", "Medium (1000-2000)", "Large (2000-5000)"]

In [80]:
size_sc = dfschool_summary.loc[:,['Average Math Score','Average Reading Score','% Passing Math','% Passing Reading','% Overall Passing Rate',]]

In [81]:
size_sc['School Size']= pd.cut(dfschool_summary['Total Students'],s_bins,labels=group_sc)

In [92]:
size_sc.count()

,Average Math Score,Average Reading Score,% Passing Math,% Passing Reading,% Overall Passing Rate
School Size,,,,,
Small (<1000),2,2,2,2,2
Medium (1000-2000),5,5,5,5,5
Large (2000-5000),8,8,8,8,8

# Scores by School Type

In [117]:
# Create a new data frame with our desired columns
scores_type = dfschool_summary[['School Type','Average Math Score',
                                  'Average Reading Score','% Passing Math',
                                  '% Passing Reading','% Overall Passing Rate',]]
scores_type

,School Type,Average Math Score,Average Reading Score,% Passing Math,% Passing Reading,% Overall Passing Rate
school_name,,,,,,
Bailey High School,[District],[77.04843247588424],[81.03396302250803],[66.68006430868168],[81.93327974276528],[74.30667202572349]
Cabrera High School,[Charter],[83.06189451022605],[83.97578040904197],[94.1334768568353],[97.03982777179763],[95.58665231431647]
Figueroa High School,[District],[76.71176670057646],[81.15801966768396],[65.98847066802306],[80.73923363852154],[73.36385215327229]
Ford High School,[District],[77.10259218692954],[80.74625775830594],[68.3096020445418],[79.29901423877328],[73.80430814165754]
Griffin High School,[Charter],[83.35149863760218],[83.816757493188],[93.39237057220708],[97.13896457765668],[95.26566757493188]
Hernandez High School,[District],[77.28975188781014],[80.9344120819849],[66.7529665587918],[80.86299892125135],[73.80798274002157]
Holden High School,[Charter],[83.80327868852459],[83.81498829039812],[92.50585480093677],[96.25292740046838],[94.37939110070258]
Huang High School,[District],[76.62941378128214],[81.18272197463148],[65.68392183750429],[81.31642098045938],[73.50017140898183]
Johnson High School,[District],[77.07246376811594],[80.96639361478681],[66.0575509346776],[81.2224322621298],[73.6399915984037]
Pena High School,[Charter],[83.83991683991684],[84.04469854469855],[94.5945945945946],[95.94594594594594],[95.27027027027026]
Rodriguez High School,[District],[76.84271067766942],[80.74468617154288],[66.36659164791197],[80.22005501375344],[73.2933233308327]
Shelton High School,[Charter],[83.3594548551959],[83.72572402044293],[93.8671209540034],[95.85462805224304],[94.86087450312323]
Thomas High School,[Charter],[83.4183486238532],[83.84892966360856],[93.27217125382263],[97.30886850152906],[95.29051987767585]
Wilson High School,[Charter],[83.2742006132282],[83.98948751642575],[93.8677179150241],[96.53964082347788],[95.20367936925099]
Wright High School,[Charter],[83.68222222222222],[83.955],[93.33333333333333],[96.61111111111111],[94.97222222222223]

In [116]:
# Create a group based off of the school type
scores_type = scores_type.groupby('School Type').mean()

DataError: No numeric types to aggregate

In [112]:
scores_stype2 = scores_stype.groupby('School Type')
scores_stype2.mean()

TypeError: unhashable type: 'numpy.ndarray'